spring.application.name=autoservice

# Adresa bazei de date MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/autoservice

# Utilizatorul MySQL
spring.datasource.username=root

# Parola utilizatorului MySQL
spring.datasource.password=root

# Driverul MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spune lui Hibernate să creeze/actualizeze tabelele după clasele Java
spring.jpa.hibernate.ddl-auto=update

# Afișează în consolă comenzile SQL executate
spring.jpa.show-sql=true

